/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ztiany_bionic_JniBridge */

#ifndef _Included_com_ztiany_bionic_JniBridge
#define _Included_com_ztiany_bionic_JniBridge
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_ztiany_bionic_JniBridge
 * Method:    testJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ztiany_bionic_JniBridge_testJni
        (JNIEnv *, jobject);


/*
 * Class:     com_apress_threads_MainActivity
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ztiany_bionic_JniBridge_nativeInit
        (JNIEnv *, jobject);

/*
 * Class:     com_apress_threads_MainActivity
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ztiany_bionic_JniBridge_nativeFree
        (JNIEnv *, jobject);

/*
 * Class:     com_apress_threads_MainActivity
 * Method:    nativeWorker
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ztiany_bionic_JniBridge_nativeWorker
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_apress_threads_MainActivity
 * Method:    posixThreads
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ztiany_bionic_JniBridge_posixThreads
        (JNIEnv *, jobject, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
