/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ztiany_CCallJava */

#ifndef _Included_ztiany_CCallJava
#define _Included_ztiany_CCallJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ztiany_CCallJava
 * Method:    javaCallC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ztiany_CCallJava_javaCallC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
