/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ztiany_JavaCallC */

#ifndef _Included_ztiany_JavaCallC
#define _Included_ztiany_JavaCallC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ztiany_JavaCallC
 * Method:    helloC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ztiany_JavaCallC_helloC
  (JNIEnv *, jclass);

/*
 * Class:     ztiany_JavaCallC
 * Method:    stringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ztiany_JavaCallC_stringFromC
  (JNIEnv *, jclass);

/*
 * Class:     ztiany_JavaCallC
 * Method:    login
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ztiany_JavaCallC_login
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ztiany_JavaCallC
 * Method:    add
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_ztiany_JavaCallC_add
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     ztiany_JavaCallC
 * Method:    cSort
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_ztiany_JavaCallC_cSort
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     ztiany_JavaCallC
 * Method:    encryption
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ztiany_JavaCallC_encryption
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
