/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ztiany_JNIErrorHandler */

#ifndef _Included_ztiany_JNIErrorHandler
#define _Included_ztiany_JNIErrorHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ztiany_JNIErrorHandler
 * Method:    testNativeThrow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ztiany_JNIErrorHandler_testNativeThrow
  (JNIEnv *, jobject);

/*
 * Class:     ztiany_JNIErrorHandler
 * Method:    testJavaThrow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ztiany_JNIErrorHandler_testJavaThrow
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
